### ISSUE TITLE
Question: why are you not translating names ?

### ISSUE THREAD

**Issue by nicolasbraun** [5etools-translated/5etools-translated.github.io#3]
Thanks for this awesome tool.

I'm working on a glossary rework and wondering why you are not translating names ?

For example looking at this Evil Mage from lmop we see that his nalme, spells, item are not translated
![image](https://github.com/5etools-translated/5etools-translated.github.io/assets/1089363/9b42e300-2b93-465b-a495-0261801186ae)

I suspect this is because of tags likes {@spells mage hand} that are used to make the links and sadly there is no proper id in the docs ?

Maybe we could translate names and tags in the exact match is in the glossary ?

Nicolas

**Comment by QuentinWidlocher** [comment]
I imagine you closed this issue because the name could not be translated, hence why you did a PR to add a glossary ? I too, would like to know why the titles can't be translated 🤔

**Comment by nicolasbraun** [comment]
Hello @QuentinWidlocher 

It's been a while but if I recall well , yes,  translating the name was **super tricky**.
- it is used in the url
- it is used in tags and tags can have a very very very wide variety of format.

The 5etoolstranslated project was also no longer working (look at the actions, it did not translated anything new in a while ) so I worked on a complete rework - that I never released because of work...

I could deep dive again but basically the idea was
- reworked the DeepL module that no longer worked
- keep the glossary system
- added a tag parser and some tag parts were translated only from glossary (by tags i mean the `@{keyword something| something2...}` syntax
- added logic to translated more keys (but maybe too much)
- also added imperial to metric conversion

The result were globally very nice but
- in French it was sometimes "overtranslated". For example the `Aid` spell in glossary was causing the verb `aid`  to be replaced in every sentence (that's how deepL glossary works)
- prone to break in case the (extra complicated) 5etool language and parsing is updated
- 
Also The translated site was too big to be deployed  on GH Pages with the language switch so there was 1 deployment per lang (and I got b*nned several times :)). The official 5etools site might have reached this limit too, I was in touch with Giddy about it.

It you are interested ping here I'll follow back on X.
